[2023-12-26 17:49:47,606:postgresql_db.py#L395:INFO]: [PostgresqlDB] Remote PostgreSQL server shut down successfully
[2023-12-26 17:49:48,141:postgresql_db.py#L378:INFO]: [PostgresqlDB] config file modification done.
[2023-12-26 17:49:48,246:postgresql_db.py#L425:INFO]: [PostgresqlDB] Remotely starting PostgreSQL server...
[2023-12-26 17:49:48,374:postgresql_db.py#L457:INFO]: [PostgresqlDB] Wait for connection to the started server...
[2023-12-26 17:49:50,396:postgresql_db.py#L467:INFO]: [PostgresqlDB] Successfully connected to the started PostgreSQL Server
[2023-12-26 17:49:50,396:postgresql_db.py#L484:INFO]: [PostgresqlDB] 2 seconds waiting for connection
[2023-12-26 17:49:50,396:postgresql_db.py#L485:INFO]: [PostgresqlDB] start command: postgres --config_file=/var/lib/postgresql/experiment/conf/tune_cnf.conf
[2023-12-26 17:49:50,396:postgresql_db.py#L486:INFO]: [PostgresqlDB] PostgresSQL is  up
[2023-12-26 17:49:50,397:postgresql_db.py#L267:INFO]: [PostgresqlDB] Sleeping for 0 seconds after restarting postgres
[2023-12-26 17:49:50,397:postgresql_db.py#L276:INFO]: [PostgresqlDB] No knobs need to be applied online
[2023-12-26 17:49:50,407:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob backend_flush_after is not successfully set to 107 (actual value: 856kB)
[2023-12-26 17:49:50,408:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob checkpoint_flush_after is not successfully set to 47 (actual value: 376kB)
[2023-12-26 17:49:50,409:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob effective_cache_size is not successfully set to 204453 (actual value: 1635624kB)
[2023-12-26 17:49:50,410:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob shared_buffers is not successfully set to 692328 (actual value: 5538624kB)
[2023-12-26 17:49:50,410:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob temp_buffers is not successfully set to 8777 (actual value: 70216kB)
[2023-12-26 17:49:50,410:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob wal_buffers is not successfully set to 234515 (actual value: 1876120kB)
[2023-12-26 17:49:50,410:postgresql_db.py#L321:INFO]: [PostgresqlDB] Knob wal_writer_flush_after is not successfully set to 364708048 (actual value: 2917664384kB)
[2023-12-26 17:49:50,411:postgresql_db.py#L282:INFO]: [PostgresqlDB] 7 knobs not successfully applied offline.
[2023-12-26 17:49:50,417:postgresql_db.py#L225:INFO]: [PostgresqlDB] Connected to PostgreSQL db for query execution:
[2023-12-26 17:49:50,417:postgresql_db.py#L229:INFO]: [PostgresqlDB] Executing /home/viktor/Experiments/CamDB/camtune/benchmarks/tpch_pgbench/18.sql
[2023-12-26 17:50:39,068:postgresql_db.py#L235:INFO]: [PostgresqlDB] Query execution failed when executing /home/viktor/Experiments/CamDB/camtune/benchmarks/tpch_pgbench/18.sql
[2023-12-26 17:55:46,720:postgresql_db.py#L396:INFO]: [PostgresqlDB] Remote PostgreSQL server shut down successfully
[2023-12-26 17:55:47,205:postgresql_db.py#L379:INFO]: [PostgresqlDB] config file modification done.
[2023-12-26 17:55:47,307:postgresql_db.py#L426:INFO]: [PostgresqlDB] Remotely starting PostgreSQL server...
[2023-12-26 17:55:47,439:postgresql_db.py#L458:INFO]: [PostgresqlDB] Wait for connection to the started server...
[2023-12-26 17:55:49,465:postgresql_db.py#L468:INFO]: [PostgresqlDB] Successfully connected to the started PostgreSQL Server
[2023-12-26 17:55:49,466:postgresql_db.py#L485:INFO]: [PostgresqlDB] 2 seconds waiting for connection
[2023-12-26 17:55:49,466:postgresql_db.py#L486:INFO]: [PostgresqlDB] start command: postgres --config_file=/var/lib/postgresql/experiment/conf/tune_cnf.conf
[2023-12-26 17:55:49,466:postgresql_db.py#L487:INFO]: [PostgresqlDB] PostgresSQL is  up
[2023-12-26 17:55:49,466:postgresql_db.py#L268:INFO]: [PostgresqlDB] Sleeping for 0 seconds after restarting postgres
[2023-12-26 17:55:49,466:postgresql_db.py#L277:INFO]: [PostgresqlDB] No knobs need to be applied online
[2023-12-26 17:55:49,477:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob backend_flush_after is not successfully set to 107 (actual value: 856kB)
[2023-12-26 17:55:49,478:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob checkpoint_flush_after is not successfully set to 47 (actual value: 376kB)
[2023-12-26 17:55:49,479:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob effective_cache_size is not successfully set to 204453 (actual value: 1635624kB)
[2023-12-26 17:55:49,480:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob shared_buffers is not successfully set to 692328 (actual value: 5538624kB)
[2023-12-26 17:55:49,480:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob temp_buffers is not successfully set to 8777 (actual value: 70216kB)
[2023-12-26 17:55:49,481:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob wal_buffers is not successfully set to 234515 (actual value: 1876120kB)
[2023-12-26 17:55:49,481:postgresql_db.py#L322:INFO]: [PostgresqlDB] Knob wal_writer_flush_after is not successfully set to 364708048 (actual value: 2917664384kB)
[2023-12-26 17:55:49,481:postgresql_db.py#L283:INFO]: [PostgresqlDB] 7 knobs not successfully applied offline.
[2023-12-26 17:55:49,489:postgresql_db.py#L225:INFO]: [PostgresqlDB] Connected to PostgreSQL server for query execution:
[2023-12-26 17:55:49,489:postgresql_db.py#L229:INFO]: [PostgresqlDB] Executing /home/viktor/Experiments/CamDB/camtune/benchmarks/tpch_pgbench/18.sql
[2023-12-26 17:56:24,659:postgresql_db.py#L235:INFO]: [PostgresqlDB] Query execution failed when executing /home/viktor/Experiments/CamDB/camtune/benchmarks/tpch_pgbench/18.sql
[2023-12-26 17:56:24,682:postgresql_db.py#L236:INFO]: [PostgresqlDB] Error information: SSL SYSCALL error: EOF detected

